// <auto-generated />
using System;
using CentralTicket.Contexts.Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralTicket.Contexts.Billing.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260526210058_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EndDate");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StartDate");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("billing_Events", "billing");
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethod");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("billing_Sales", "billing");
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("Kind");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SaleId");

                    b.ToTable("billing_Tickets", "billing");
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("billing_Users", "billing");
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Event", b =>
                {
                    b.OwnsOne("CentralTicket.Contexts.Billing.ValueObjects.TicketAmount", "TicketAmount", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("TicketAmount");

                            b1.HasKey("EventId");

                            b1.ToTable("billing_Events", "billing");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("CentralTicket.Contexts.Billing.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Title");

                            b1.HasKey("EventId");

                            b1.ToTable("billing_Events", "billing");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("TicketAmount")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Sale", b =>
                {
                    b.HasOne("CentralTicket.Contexts.Billing.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CentralTicket.Contexts.Billing.ValueObjects.Price", "TotalValue", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalValue");

                            b1.HasKey("SaleId");

                            b1.ToTable("billing_Sales", "billing");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("CentralTicket.Contexts.Billing.ValueObjects.OrderCode", "OrderCode", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("OrderCode");

                            b1.HasKey("SaleId");

                            b1.ToTable("billing_Sales", "billing");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("OrderCode")
                        .IsRequired();

                    b.Navigation("TotalValue")
                        .IsRequired();
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Ticket", b =>
                {
                    b.HasOne("CentralTicket.Contexts.Billing.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentralTicket.Contexts.Billing.Entities.Sale", null)
                        .WithMany("PurchasedTickets")
                        .HasForeignKey("SaleId");

                    b.OwnsOne("CentralTicket.Contexts.Billing.ValueObjects.Price", "Value", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Value");

                            b1.HasKey("TicketId");

                            b1.ToTable("billing_Tickets", "billing");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Event");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("CentralTicket.Contexts.Billing.Entities.Sale", b =>
                {
                    b.Navigation("PurchasedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
